### PR TITLE
Added support for terminating a spawned worker if a timeout is reached

### PR DESCRIPTION
**Pull request by amit777**
Hi, I found this lib because I was searching for a way to easily spawn a worker, but also be able to terminate it if a timeout is reached.  The use case is that I want to time limit execution for certain operations. 

I don't have any experience with the test frameworks in this lib, but if my pull request looks promising, I'm happy to learn and create a test spec.  But only if you think this extra feature even belongs in parallel.js?

### CODE REVIEW

**Review by mathiasrw — CHANGES_REQUESTED** [review]
Epic. Please also add a description of the new option in the readme file too.

**Comment by amit777** [comment]
Thanks! I've added an update to the documentation.  However, is it possible that the new timeout option will overwrite an environment variable that could be set in the Parallel constructor?

**Review by mathiasrw — APPROVED** [review]

**Comment by mathiasrw** [comment]
Thank you!

**Comment by mathiasrw** [comment]
released as part of v1.1.0

**Pull request merged**
