### PR TITLE
Getting green Travis tests

### PR DESCRIPTION
**Pull request by mathiasrw**

### CODE REVIEW

**Comment by amilajack** [comment]
These commits undo the purpose of even having tests and a linter in the first place. We shouldn't get green travis tests simply by disabling our tests. This module isn't usable right now. I think we should let users know that by showing that the build is failing. Also for all future PR's, I think it would be better if weyou could get feedback from others before PR'ing to master.

**Comment by mathiasrw** [comment]
For everyone to get on track with development without disturbing each other its is priority that the tests get up and running. This way the travis test can be used to verify each PR. 

What was done with this PR was to 

1. Disable a peformance test that had an hardcoded expected run time that failed on the travis platform. 
2. Disable ESlint test as none of the code was linted (so it makes no point to do a travis test on that)

Disabling the tests does not get tests up and running - but disabling elements that does not directly check for module correctness while blocking for efficient development makes good sense.

**Comment by amilajack** [comment]
> Disable ESlint test as none of the code was linted

They will eventually be linted. Unfortunately the branch on which I was fixing linter errors was deleted. There's no 

> For everyone to get on track with development without disturbing each other its is priority that the tests get up and running

How do tests conflict with our teamwork? Every single project that I have contributed to (especially those over 5000K stars) run linters in their tests. These teams are much bigger than ours. If you want to test specific things then instead of disabling tests to give the false impression that things are passing, we should run specific tests one by one and temporarily allow for the failure of certain tests.

**Comment by mathiasrw** [comment]
Having linting as breaking build tests makes perfect sense when the code is linted, so you can make sure everyone is following same structure. 

Letting linting break build tests before the code limits you from using CI tests to see if the commit broke functionality.

**Comment by amilajack** [comment]
https://travis-ci.org/parallel-js/parallel.js/jobs/163415395
screen shot 2016-09-28 at 9 31 04 am

**Pull request merged**
