### PR TITLE
Progress events w/message data and partial results

### PR DESCRIPTION
**Pull request by mrunderhill89**
Just added onto blackrabbit99's "progress events" fork. This code allows you to get index and data information from a `map` or `reduce` call without having to wait for every process to finish like if you used `then`.

### CODE REVIEW

**Comment by cloppy** [comment]
Any progress on merging this? Would be great not to have manual edit the file every time I install the module.

**Comment by mathiasrw** [comment]
Hi @mrunderhill89 

Thanks for a great effort. 

We are some new people who just got involved to blow some life into the development. 

I will keep this open and work towards merging your commits

**Comment by amilajack** [comment]
@mrunderhill89 please rebase your commits and we can merge this :)

**Comment by mrunderhill89** [comment]
Sounds good, though I've never rebased a project before. Any idea on how to do that?

**Comment by amilajack** [comment]
Merging is fine. But the conflicts have to be fixed.

**Comment by pmunin** [comment]
is there any update on that?

**Comment by aliflux-omo** [comment]
Any update on this?

**Pull request closed without merging**
