### PR TITLE
Webworker node

### PR DESCRIPTION
**Pull request by dre-hh**
plz review but don't merge, as specs are missing

started a pull request for review the necessary changes for #100.
optional dependency to webworker_thread ^0.4.7 due to intorduced []bug fixes[1] in webworker api
used parallel.js

[1]: https://github.com/audreyt/node-webworker-threads/blob/master/CHANGES.md

### CODE REVIEW

**Comment by dre-hh** [comment]
why are some specs skipped on node?
`if(isNode) return;` and than later on, there is a check for node 
`var p = new Parallel([1, 2, 3], { evalPath: isNode ? undefined : 'lib/eval.js', maxWorkers: 2 });`
https://github.com/adambom/parallel.js/blob/master/test/specs/api.spec.js#L142

**Comment by Sebmaster** [comment]
> why are some specs skipped on node?

Looks to me like those are all the tests which throw an error. Chances are something with error serialization is off, but I can't quite remember now.

**Comment by mathiasrw** [comment]
@dre-hh Is this still relevant, or should I close it?

**Comment by amilajack** [comment]
Closing due to no response

**Pull request closed without merging**
