### PR TITLE
Make import work in node 13 ESM

### PR DESCRIPTION
**Pull request by benbucksch**
Fixes issue #187 error: "Cannot find main entry point" in package.json

### CODE REVIEW

**Comment by benbucksch** [comment]
After merging this, could you please update the [npm package](https://www.npmjs.com/package/paralleljs)?

**Comment by mathiasrw** [comment]
Thank you!

**Comment by benbucksch** [comment]
@mathiasrw : Thank you for merging it so quickly!

Would it be possible to update the npm package? To fix #187 and #188.

**Comment by mathiasrw** [comment]
Ill see what I can do. Not sure I have access more.

**Comment by MaXFalstein** [comment]
> Ill see what I can do. Not sure I have access more.

I do not remember any of us ever having NPM or package access.

**Comment by mathiasrw** [comment]
Nope - I dont have access. Last update was 6 years ago. Time for an npm name change?

**Comment by benbucksch** [comment]
$ npm owner ls paralleljs
asavitzky <adam.savitzky@gmail.com>

**Comment by MaXFalstein** [comment]
I would prefer not to have to change the NPM name.
@mathiasrw, who has had contact wih Adam?
I do not think I have. Everything has been through @amilajack or you.

**Comment by benbucksch** [comment]
Enlightening (less bureaucratic than I thought!): https://docs.npmjs.com/using-npm/disputes.html

**Comment by mathiasrw** [comment]
@benbucksch There is no dispute. The repo is adams, the npm is adams. A dispute would be if we insists that we have the right to the npm name. We dont. We contribute with the rights as the originator see fit.

**Comment by benbucksch** [comment]
Mathias, yes, of course. The title of the document is a bit misleading, but it's also for an unresponsive maintainer. (6 years without releases is something!)

Did you contact adams by email? Did he respond? Will he make the release? If yes, no problem, all good. If no, you can make releases again via this process.

**Comment by mathiasrw** [comment]
@benbucksch Ok. You are right. I sent him an email cc npm.

**Comment by mathiasrw** [comment]
image

**Comment by MaXFalstein** [comment]
Incredible response time; great support so far 👍🏼

**Comment by mathiasrw** [comment]
Merged and pushed to npm as version 1.0.0

**Comment by benbucksch** [comment]
That's great! Thank you!

**Pull request merged**
