### PR TITLE
Rewrite/Migration 👷 🚗 (WIP)

### PR DESCRIPTION
**Pull request by amilajack**
Please don't merge this yet, as this is a work in progress
- [ ] Add initial browser tests
- [ ] Rewrite
- [ ] Create different node and browser builds

### CODE REVIEW

**Comment by amilajack** [comment]
This is far from being finished. I changed the title of this pr to make it more accurate.

**Comment by jefffriesen** [comment]
What's the status of this PR? Is there a plan to merge it?

**Comment by amilajack** [comment]
I've been held back by other projects. Haven't had time to look into this project a lot anymore. But when JS gets multithreading primitives, I will be sure to look into this PR rewrite this entire project. Also doesn't have any real tests so its hard for us to find out if this works or not

**Comment by jefffriesen** [comment]
Wow - when are multithreaded primitives expected?

**Comment by jefffriesen** [comment]
Sorry, didn't mean to make you google something that I can google.

https://hacks.mozilla.org/2016/05/a-taste-of-javascripts-new-parallel-primitives/

I read that article about a year ago, but I haven't heard we were close to getting it (or Babel being able to polyfill it). When I read your response I got the impression it was imminent.

**Comment by amilajack** [comment]
ES2018 I think. They're stage 4 I think

**Comment by amilajack** [comment]
Cant find it on the [proposals page](https://github.com/tc39/proposals) but here's a [short discussion between a tc39 member and I](https://github.com/amilajack/eslint-plugin-compat/issues/61)

**Comment by TheLarkInn** [comment]
Initially I believed I saw studies on this meaning to leverage GPU's parallel processing, but this just looks to be using webworkers to create threads. Is there something I'm incorrect on with that statement?

**Comment by amilajack** [comment]
@TheLarkInn that's correct. I actually wouldn't recommend using this project (at least at this point). I'd recommend https://github.com/rvagg/node-worker-farm

**Comment by TheLarkInn** [comment]
http://on-demand.gputechconf.com/gtc/2014/presentations/S4168-accelerated-javascript-accessing-gpus.pdf Last page. Maybe this is where I was confused.

**Comment by TheLarkInn** [comment]
Thanks for the info @amilajack, maybe wrong place to ask but do you know of any further research or continuing investment on leveraging GPU based parallelism?

**Comment by amilajack** [comment]
Hmm I'm not sure. Are your asking about resources that discuss leveraging GPU's to compile/execute JS? So like a GPU JIT?

Here's [some research](https://github.com/amilajack/reading/blob/master/JavaScript/A%20Limit%20Study%20of%20Javascript%20Parallelism.pdf) that doesn't leverage GPU's but parallelizes JS

> maybe wrong place to ask but do you know of any further research or continuing investment on leveraging GPU based parallelism?

These might be of use to you:
* http://gpu.rocks
* https://github.com/MaiaVictor/WebMonkeys

**Comment by TheLarkInn** [comment]
Thanks those are on my hotlist!

**Pull request closed without merging**
